import type * as React from 'react';
import type { Root } from 'react-dom/client';
import { bulkFailures, valueFromInput, type BulkResult, type Action, type Condition, type Finding, type Policy, type Scan } from './model';
declare const wp: { element: typeof React & {createRoot(el: Element): Root}; i18n: {__(value: string, domain: string): string}; components: { Spinner: React.ComponentType } };
declare const CFConfig: {root: string; nonce: string; caps: Record<string, boolean>; locale: string; timezone: string; rtl: boolean};
const {createElement: h, Fragment, useEffect, useState, useRef} = wp.element;
const __ = (value: string) => wp.i18n.__(value, 'content-firewall');
function date(value: string): string { const parsed = new Date(value.replace(' ', 'T') + 'Z'); try {return new Intl.DateTimeFormat(CFConfig.locale.replace('_','-'), {dateStyle:'medium',timeStyle:'short', timeZone:CFConfig.timezone}).format(parsed);} catch {return value + ' UTC';} }
async function api<T>(path: string, data?: unknown): Promise<T> {
  const [route, query] = path.split('?', 2); const url = new URL(CFConfig.root);
  if (url.searchParams.has('rest_route')) url.searchParams.set('rest_route', url.searchParams.get('rest_route')!.replace(/\/$/,'') + route); else url.pathname = url.pathname.replace(/\/$/,'') + route;
  if (query) new URLSearchParams(query).forEach((value,key) => url.searchParams.set(key,value));
  const response = await fetch(url, {method: data === undefined ? 'GET' : 'POST', credentials: 'same-origin', headers: {'X-WP-Nonce': CFConfig.nonce, 'Content-Type': 'application/json'}, body: data === undefined ? undefined : JSON.stringify(data)});
  const result = await response.json(); if (!response.ok) throw new Error(result.message ?? __('Request failed.')); return result as T;
}
const actions: Action[] = ['ALLOW', 'SANITIZE', 'REVIEW', 'QUARANTINE', 'BLOCK'];
function ConditionEditor({value, change, depth = 0}: {value: Condition; change(v: Condition): void; depth?: number}) {
  if ('group' in value) return <fieldset className="cf-condition"><legend>{__('Condition group')}</legend>
    <label>{__('Match')} <select value={value.group} onChange={e => change({...value, group: e.target.value as 'AND' | 'OR' | 'NOT', children: e.target.value === 'NOT' ? value.children.slice(0, 1) : value.children})}><option value="AND">{__('All conditions (AND)')}</option><option value="OR">{__('Any condition (OR)')}</option><option value="NOT">{__('Negate condition (NOT)')}</option></select></label>
    {value.children.map((child, i) => <div key={i}><ConditionEditor value={child} depth={depth + 1} change={v => change({...value, children: value.children.map((c, index) => index === i ? v : c)})}/>{value.children.length > 1 && <button type="button" className="button" onClick={() => change({...value, children: value.children.filter((_, index) => index !== i)})}>{__('Remove condition')}</button>}</div>)}
    {value.group !== 'NOT' && value.children.length < 32 && <button type="button" className="button" onClick={() => change({...value, children: [...value.children, {field: 'context', op: 'eq', value: 'avatar'}]})}>{__('Add condition')}</button>}
    {depth < 7 && value.group !== 'NOT' && <button type="button" className="button" onClick={() => change({...value, children: [...value.children, {group: 'OR', children: [{field: 'context', op: 'eq', value: 'media'}]}]})}>{__('Add nested group')}</button>}
  </fieldset>;
  return <div className="cf-rule-fields"><label>{__('Signal')}<input value={value.field} onChange={e => change({...value, field: e.target.value})} list="cf-signals"/></label><label>{__('Comparison')}<select value={value.op} onChange={e => change({...value, op: e.target.value})}>{['eq', 'ne', 'gte', 'gt', 'lte', 'lt', 'contains', 'in', 'between', 'domain', 'regex', 'exists'].map(op => <option key={op}>{op}</option>)}</select></label>{value.op !== 'exists' && <label>{__('Value')}<input value={Array.isArray(value.value) ? value.value.join(',') : String(value.value ?? '')} onChange={e => {try {change({...value, value: valueFromInput(value.op, e.target.value)});} catch {change({...value, value: e.target.value});}}}/></label>}</div>;
}
function Policies({notice}: {notice(s: string): void}) {
  const [policy, setPolicy] = useState<Policy>(); const [presets, setPresets] = useState<Policy[]>([]); const [sample, setSample] = useState('0.75'); const [simulation, setSimulation] = useState<string>(''); const [busy, setBusy] = useState(false);
  useEffect(() => {api<Policy>('/policy').then(setPolicy).catch(e => notice(e.message)); api<Policy[]>('/presets').then(setPresets).catch(e => notice(e.message));}, []);
  if (!policy) return <wp.components.Spinner/>;
  const changeRule = (i: number, change: Partial<Policy['rules'][number]>) => setPolicy({...policy, rules: policy.rules.map((r, index) => index === i ? {...r, ...change} : r)});
  return <section><h2>{__('Policies')}</h2><p>{__('Rules run in priority order. File security checks always apply. Every save creates an immutable version.')}</p>
    <div className="cf-toolbar"><label>{__('Start from a preset')}<select value="" onChange={e => {const p = presets.find(p => p.id === e.target.value); if (p) setPolicy(structuredClone(p));}}><option value="">{__('Choose a preset…')}</option>{presets.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{__('Policy name')}<input value={policy.name} onChange={e => setPolicy({...policy, name: e.target.value})}/></label><label><input type="checkbox" checked={policy.shadow} onChange={e => setPolicy({...policy, shadow: e.target.checked})}/>{__('Monitor content decisions')}</label></div>
    <div className="cf-toolbar"><label>{__('Provider failure')}<select value={String(policy.options.failure_mode ?? 'QUARANTINE')} onChange={e => setPolicy({...policy, options: {...policy.options, failure_mode: e.target.value}})}><option value="QUARANTINE">{__('Hold privately')}</option><option value="FAIL_CLOSED">{__('Block')}</option><option value="FAIL_OPEN">{__('Allow when content provider fails')}</option></select></label><label><input type="checkbox" checked={Boolean(policy.options.requires_content)} onChange={e => setPolicy({...policy, options: {...policy.options, requires_content: e.target.checked}})}/>{__('Require remote content moderation')}</label></div>
    <datalist id="cf-signals">{['sexual.explicit','sexual.suggestive','violence.graphic','weapon.firearm','pii.phone','pii.email','context','roles','post_type','bytes','width','height','trust','site_id','ocr_text'].map(f => <option key={f} value={f}/>)}</datalist>
    {policy.rules.map((rule, i) => <fieldset key={rule.id} className="cf-card"><legend>{__('Rule')} {i + 1}</legend><div className="cf-toolbar"><label>{__('Identifier')}<input value={rule.id} onChange={e => changeRule(i, {id: e.target.value})}/></label><label>{__('Priority')}<input type="number" value={rule.priority} onChange={e => changeRule(i, {priority: Number(e.target.value)})}/></label><label><input type="checkbox" checked={rule.enabled} onChange={e => changeRule(i, {enabled: e.target.checked})}/>{__('Enabled')}</label></div>
      <ConditionEditor value={rule.condition} change={condition => changeRule(i, {condition})}/><label>{__('Then')} <select value={rule.action} onChange={e => changeRule(i, {action: e.target.value as Action})}>{actions.map(a => <option key={a}>{a}</option>)}</select></label>
      <div className="cf-toolbar"><button type="button" className="button" onClick={() => setPolicy({...policy, rules: [...policy.rules, {...structuredClone(rule), id: rule.id + '-copy-' + policy.rules.length}]})}>{__('Duplicate rule')}</button><button type="button" className="button" onClick={() => setPolicy({...policy, rules: policy.rules.filter((_, index) => index !== i)})}>{__('Remove rule')}</button></div></fieldset>)}
    <div className="cf-toolbar"><button className="button" onClick={() => setPolicy({...policy, rules: [...policy.rules, {id: 'rule-' + crypto.randomUUID().slice(0, 8), priority: 10, enabled: true, condition: {group: 'AND', children: [{field: 'sexual.explicit', op: 'gte', value: 0.85}]}, action: 'REVIEW'}]})}>{__('Add rule')}</button><button className="button button-primary" disabled={busy} onClick={async () => {setBusy(true); try {const p = await api<Policy>('/policy/save', policy); setPolicy(p); notice(__('Policy version saved.'));} catch (e) {notice((e as Error).message);} finally {setBusy(false);}}}>{__('Save new version')}</button></div>
    <details className="cf-card"><summary>{__('Confidence bands')}</summary><p>{__('Presets send concerning signals to review. Enable automatic blocking only after validating precision on your own lawful corpus.')}</p>{Object.entries(policy.bands).map(([category, band]) => <div key={category} className="cf-toolbar"><strong>{category}</strong><label>{__('Review from')}<input type="number" min="0" max="1" step="0.01" value={band.review} onChange={e => setPolicy({...policy, bands: {...policy.bands, [category]: {...band, review: Number(e.target.value)}}})}/></label><label>{__('Block from')}<input type="number" min="0" max="1" step="0.01" value={band.block} onChange={e => setPolicy({...policy, bands: {...policy.bands, [category]: {...band, block: Number(e.target.value)}}})}/></label><label><input type="checkbox" checked={band.calibrated} onChange={e => setPolicy({...policy, bands: {...policy.bands, [category]: {...band, calibrated: e.target.checked}}})}/>{__('Validated calibration')}</label></div>)}</details>
    <div className="cf-card"><h3>{__('Test without publishing')}</h3><label>{__('Synthetic explicit-content score')} <input type="number" min="0" max="1" step="0.01" value={sample} onChange={e => setSample(e.target.value)}/></label><button className="button" onClick={async () => {try {const result = await api<{action: string; rules: string[]}>('/simulation', {policy, signals: {context: 'avatar'}, findings: [{category: 'sexual.explicit', confidence: Number(sample), provider: 'synthetic', model: '1'}]}); setSimulation(result.action + ' · ' + (result.rules.join(', ') || __('Default or confidence band')));} catch (e) {notice((e as Error).message);}}}>{__('Simulate')}</button><p role="status">{simulation}</p></div>
  </section>;
}
function Queue({notice}: {notice(s: string): void}) {
  const [rows, setRows] = useState<Scan[]>([]); const [state, setState] = useState(''); const [after, setAfter] = useState(0); const [selected, setSelected] = useState<Set<string>>(new Set()); const [detail, setDetail] = useState<(Scan & {notes: {actor_id: string; action: string; reason: string; created_at: string}[]; findings: Finding[]; decision: {action: string; reasons: string[]; rules: string[]}})>(); const [preview, setPreview] = useState(''); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const revealRef = useRef<HTMLButtonElement>(null);
  const requestId = useRef(0); const detailRequest = useRef(0);
  const load = async () => {const token = ++requestId.current; setBusy(true); try {const data = await api<Scan[]>('/scans?after=' + after + '&state=' + encodeURIComponent(state)); if (token === requestId.current) {setRows(data); setSelected(new Set());}} catch (e) {if (token === requestId.current) notice((e as Error).message);} finally {if (token === requestId.current) setBusy(false);}};
  useEffect(() => {setRows([]); setSelected(new Set()); setDetail(undefined); setPreview(''); detailRequest.current++; void load(); return () => {requestId.current++; detailRequest.current++;};}, [state, after]);
  const act = async (action: string, items: Scan[]) => {if (!items.length || busy) return; if (reason.trim().length < 3) {notice(__('Enter a reason of at least three characters.')); return;} setBusy(true); try {const results = await api<BulkResult[]>('/bulk', {items: items.map(r => ({id: Number(r.id), revision: Number(r.revision)})), action, reason}); const failures = bulkFailures(results); notice(failures.length ? __('Some actions failed: ') + failures.join(' · ') : __('Moderation action recorded.')); setDetail(undefined); setPreview(''); detailRequest.current++; setSelected(new Set()); await load();} catch (e) {notice((e as Error).message);} finally {setBusy(false);}};
  return <section><h2>{__('Moderation queue')}</h2><p>{__('Uploads held here remain private. Approval publishes a security-checked derivative. Sensitive previews require an explicit reveal.')}</p>
    <div className="cf-toolbar"><label>{__('View')}<select aria-label={__('View')} disabled={busy} value={state} onChange={e => {setState(e.target.value); setAfter(0);}}><option value="">{__('All records')}</option>{['PENDING_PROVIDER','REVIEW_REQUIRED','QUARANTINED','ALLOWED','BLOCKED','APPEALED','FAILED'].map(s => <option key={s}>{s}</option>)}</select></label><button className="button" disabled={busy} onClick={load}>{__('Refresh')}</button></div>
    {busy && <wp.components.Spinner/>}<table className="widefat striped"><caption className="screen-reader-text">{__('Private moderation cases')}</caption><thead><tr><th>{__('Select')}</th><th>{__('File / case')}</th><th>{__('State')}</th><th>{__('Risk signal')}</th><th>{__('Created')}</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><input type="checkbox" aria-label={__('Select case') + ' ' + row.id} checked={selected.has(row.id)} onChange={e => {const next = new Set(selected); e.target.checked ? next.add(row.id) : next.delete(row.id); setSelected(next);}}/></td><td><button className="button-link" disabled={busy} onClick={async () => {const token = ++detailRequest.current; setPreview(''); setDetail(undefined); try {const value = await api<NonNullable<typeof detail>>('/scans/' + row.id); if (token === detailRequest.current) setDetail(value);} catch (e) {if (token === detailRequest.current) notice((e as Error).message);}}}>{row.file_name}</button> <small>#{row.id}</small></td><td><span className="cf-state">{row.state}</span></td><td>{Number(row.risk).toLocaleString(CFConfig.locale.replace('_', '-'), {style: 'percent'})}</td><td>{date(row.created_at)}</td></tr>)}</tbody></table>{!rows.length && !busy && <p className="cf-empty">{__('No cases match this view.')}</p>}
    <div className="cf-toolbar"><button className="button" disabled={!after || busy} onClick={() => setAfter(0)}>{__('First page')}</button><button className="button" disabled={rows.length < 30 || busy} onClick={() => setAfter(Number(rows[rows.length - 1].id))}>{__('Next page')}</button></div>
    <label className="cf-reason">{__('Required moderation reason')}<textarea value={reason} onChange={e => setReason(e.target.value)} maxLength={2000}/></label><div className="cf-toolbar"><button className="button button-primary" disabled={!selected.size || busy} onClick={() => act('approve', rows.filter(r => selected.has(r.id)))}>{__('Approve selected')}</button><button className="button" disabled={!selected.size || busy} onClick={() => act('reject', rows.filter(r => selected.has(r.id)))}>{__('Reject selected')}</button></div>
    {detail && <div className="cf-card"><h3>{detail.file_name} · #{detail.id}</h3><p><strong>{detail.decision.action}</strong> · {detail.decision.reasons.join(', ')} · {detail.decision.rules.join(', ')}</p><p className="cf-warning">{__('Content warning: this preview may contain sensitive or disturbing material.')}</p>{preview ? <><img className="cf-preview" src={preview} alt={__('Revealed moderation preview')}/><button className="button" onClick={() => {setPreview(''); revealRef.current?.focus();}}>{__('Hide preview')}</button></> : <button ref={revealRef} className="button" disabled={busy || !CFConfig.caps.reveal_sensitive_content} onClick={async () => {try {const token = detailRequest.current; const result = await api<{mime: string; content: string}>('/scans/' + detail.id + '/preview'); if (!['image/jpeg','image/png','image/gif','image/webp','image/avif'].includes(result.mime)) throw new Error(__('Unsupported preview.')); if (token !== detailRequest.current) return; setPreview('data:' + result.mime + ';base64,' + result.content);} catch (e) {notice((e as Error).message);}}}>{__('Reveal sensitive preview')}</button>}
      <details><summary>{__('Moderator notes and rationale')}</summary>{detail.notes.map((note,i) => <p key={i}><strong>{note.action}</strong> · {date(note.created_at)} · {note.reason}</p>)}</details><table className="widefat"><caption>{__('Normalized evidence')}</caption><thead><tr><th>{__('Category')}</th><th>{__('Score and scale')}</th><th>{__('Provider / model')}</th></tr></thead><tbody>{detail.findings.map((f,i) => <tr key={i}><td>{f.category}</td><td>{f.confidence.toFixed(3)} ({f.scale})</td><td>{f.provider} / {f.model}</td></tr>)}</tbody></table><div className="cf-toolbar">{['approve','reject','rescan','fingerprint','escalate','note'].map(action => <button key={action} className="button" disabled={busy} onClick={() => act(action, [detail])}>{action}</button>)}<button className="button" onClick={() => {setDetail(undefined); setPreview(''); detailRequest.current++;}}>{__('Close case')}</button></div></div>}
  </section>;
}
function DataView({path, title, notice}: {path: string; title: string; notice(s: string): void}) {
  const [data, setData] = useState<unknown>(); useEffect(() => {let active = true; setData(undefined); api(path).then(value => {if (active) setData(value);}).catch(e => {if (active) notice(e.message);}); return () => {active = false;};}, [path]);
  function render(value: unknown, depth = 0): React.ReactNode {
    if (value === null || value === undefined) return '—';
    if (typeof value !== 'object') return <span>{String(value)}</span>;
    if (Array.isArray(value)) return value.length ? <ul className="cf-records">{value.map((item, i) => <li key={i}>{render(item, depth + 1)}</li>)}</ul> : <p>{__('No records yet.')}</p>;
    return <dl className="cf-facts">{Object.entries(value).map(([key, item]) => <div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{render(item, depth + 1)}</dd></div>)}</dl>;
  }
  return <section><h2>{title}</h2>{data === undefined ? <wp.components.Spinner/> : render(data)}</section>;
}
function Settings({notice}: {notice(s: string): void}) {
  const [settings, setSettings] = useState<Record<string, number | boolean>>(); useEffect(() => {api<Record<string, number | boolean>>('/settings').then(setSettings).catch(e => notice(e.message));}, []);
  if (!settings) return <wp.components.Spinner/>;
  return <section><h2>{__('Settings')}</h2><p>{__('Security limits apply to every uploader. Configure a persistent private directory and scanner credentials in wp-config.php or environment variables.')}</p><form onSubmit={async e => {e.preventDefault(); try {await api('/settings/save', Object.fromEntries(Object.entries(settings).filter(([,value]) => typeof value === 'boolean' || typeof value === 'number'))); notice(__('Settings saved.'));} catch (e) {notice((e as Error).message);}}}>{Object.entries(settings).filter(([,value]) => typeof value === 'boolean' || typeof value === 'number').map(([key, value]) => <label className="cf-setting" key={key}>{key.replaceAll('_', ' ')}{typeof value === 'boolean' ? <input type="checkbox" checked={value} onChange={e => setSettings({...settings, [key]: e.target.checked})}/> : <input type="number" min="1" value={value} onChange={e => setSettings({...settings, [key]: Number(e.target.value)})}/>}</label>)}<button className="button button-primary">{__('Save settings')}</button></form></section>;
}
function App() {
  const [view, setView] = useState('dashboard'); const [message, setMessage] = useState(''); const heading = useRef<HTMLHeadingElement>(null);
  const views = [{id:'dashboard', label:__('Dashboard'), cap:'view_content_firewall_analytics'}, {id:'queue', label:__('Moderation Queue'), cap:'review_content_firewall_queue'}, {id:'policies', label:__('Policies'), cap:'manage_content_firewall_policies'}, {id:'scanner', label:__('Media Scanner'), cap:'manage_content_firewall'}, {id:'providers', label:__('Providers'), cap:'manage_content_firewall_providers'}, {id:'analytics', label:__('Analytics'), cap:'view_content_firewall_analytics'}, {id:'audit', label:__('Audit Log'), cap:'view_content_firewall_audit'}, {id:'integrations', label:__('Integrations'), cap:'manage_content_firewall_integrations'}, {id:'health', label:__('System Health'), cap:'manage_content_firewall'}, {id:'settings', label:__('Settings'), cap:'manage_content_firewall'}, {id:'developer', label:__('Developer Tools'), cap:'manage_content_firewall'}, {id:'my-uploads', label:__('My Uploads'), cap:''}].filter(v => !v.cap || CFConfig.caps[v.cap]);
  useEffect(() => {if (!views.some(v => v.id === view)) setView('my-uploads');}, []);
  return <div className="cf-shell" dir={CFConfig.rtl ? 'rtl' : 'ltr'}><header><span className="cf-eyebrow">{__('UPLOAD GOVERNANCE')}</span><h1 ref={heading} tabIndex={-1}>{__('Content Firewall')}</h1><p>{__('Private review. Clear policy. Safer publishing.')}</p></header><div className="cf-layout"><nav aria-label={__('Content Firewall navigation')}>{views.map(v => <button key={v.id} aria-current={view === v.id ? 'page' : undefined} onClick={() => {setView(v.id); setMessage(''); heading.current?.focus();}}>{v.label}</button>)}</nav><main><div role="status" aria-live="polite" className={message ? 'cf-notice' : ''}>{message}</div>
    {['dashboard','analytics'].includes(view) && <DataView path="/analytics" title={view === 'dashboard' ? __('Overview · last 30 days') : __('Analytics')} notice={setMessage}/>}
    {view === 'queue' && <Queue notice={setMessage}/>}{view === 'policies' && <Policies notice={setMessage}/>}{view === 'settings' && <Settings notice={setMessage}/>}
    {['providers','audit','health','my-uploads'].includes(view) && <DataView path={'/' + view} title={views.find(v => v.id === view)?.label ?? ''} notice={setMessage}/>}
    {view === 'scanner' && <section><h2>{__('Existing media scanner')}</h2><p>{__('Scan the library in resumable batches. Existing local files remain accessible until a scan decision. Held decisions remove local public derivatives; cached and offloaded copies need separate controls.')}</p><button className="button button-primary" onClick={async () => {try {await api('/library', {}); setMessage(__('Library scan queued.'));} catch (e) {setMessage((e as Error).message);}}}>{__('Queue library scan')}</button><button className="button" onClick={async () => {try {await api('/worker', {}); setMessage(__('Worker batch finished.'));} catch (e) {setMessage((e as Error).message);}}}>{__('Run worker batch')}</button></section>}
    {view === 'integrations' && <section><h2>{__('Integrations')}</h2><p>{__('Media Library, REST media, AJAX uploads and sideloads use the WordPress upload gateway. Custom integrations must submit files through the governed upload interface.')}</p><p>{__('Configure signed webhooks through deployment configuration. Do not include file content or extracted text in notifications.')}</p></section>}
    {view === 'developer' && <section><h2>{__('Developer tools')}</h2><p>{__('Use the versioned REST API and wp content-firewall commands for automation. Diagnostics exclude credentials, raw files and OCR text.')}</p><button className="button" onClick={async () => {try {const report = await api('/health'); const url = URL.createObjectURL(new Blob([JSON.stringify(report,null,2)], {type:'application/json'})); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'content-firewall-diagnostics.json'; anchor.click(); URL.revokeObjectURL(url);} catch (e) {setMessage((e as Error).message);}}}>{__('Download diagnostics')}</button></section>}
  </main></div><footer>{__('No product telemetry. Provider processing follows your site configuration.')}</footer></div>;
}
const mount = document.getElementById('cf-app'); if (mount) wp.element.createRoot(mount).render(<App/>);
