import type * as React from 'react';
import {api, __, date} from './transport';
import {bulkFailures,intlLocale,type BulkResult,type Finding,type Scan} from './model';
declare const wp: {element:typeof React;components:{Spinner:React.ComponentType}};
declare const CFConfig: {caps:Record<string,boolean>;locale:string};
const {createElement:h,Fragment,useState,useEffect,useRef}=wp.element;
type Reviewer={id:number;name:string};
type Assignment={team:string;priority:number;sla_at:string|null};
type Provenance={state:string;signature_valid:boolean|null;trusted:boolean|null;ai_declared:boolean|null;issuer:string;actions:string[]};
type Detail=Scan&{signals_json?:string;notes:{actor_id:string;action:string;reason:string;created_at:string}[];findings:Finding[];decision:{action:string;reasons:string[];rules:string[]};case?:{owner_id:string;team:string;priority:string;sla_at:string|null};appeals?:{reason:string;status:string;resolution:string;created_at:string}[]};
function Credentials({detail}: {detail:Detail}) {
  let report:Provenance|undefined;try{report=JSON.parse(detail.signals_json??'{}').provenance;}catch{return null;}if(!report)return null;
  const measured=(value:boolean|null)=>value===null?__('Not established'):value?__('Yes'):__('No');
  return <details><summary>{__('Original Content Credentials')}</summary><p>{__('This report concerns the private original. Reconstructed public media does not preserve its credentials. An absent credential does not establish that content is fake, and signature validity does not establish signer trust.')}</p><dl className="cf-facts"><div><dt>{__('Credential state')}</dt><dd>{report.state}</dd></div><div><dt>{__('Signature and asset binding valid')}</dt><dd>{measured(report.signature_valid)}</dd></div><div><dt>{__('Signer trusted')}</dt><dd>{measured(report.trusted)}</dd></div><div><dt>{__('AI use declared')}</dt><dd>{measured(report.ai_declared)}</dd></div><div><dt>{__('Issuer')}</dt><dd>{report.issuer||__('Not established')}</dd></div><div><dt>{__('Declared actions')}</dt><dd>{report.actions.join(', ')||__('None')}</dd></div></dl></details>;
}
type View={id:string;name:string;state:string;owner:number;team:string;overdue:boolean};
type Extra={owner_id?:number;assignment?:Assignment;confirm?:boolean};
type Confirmation={action:string;items:Scan[];extra:Extra};
const actionLabels=()=>({approve:__('Approve'),reject:__('Reject'),quarantine:__('Quarantine'),delete:__('Delete private original'),rescan:__('Rescan'),fingerprint:__('Block fingerprint'),escalate:__('Escalate'),note:__('Add note')});
function Confirm({request,complete,cancel}: {request:Confirmation;complete():void;cancel():void}) {
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const node=dialog.current;node?.showModal();return()=>node?.close();},[]);
  return <dialog ref={dialog} aria-labelledby="cf-confirm-title" onCancel={e=>{e.preventDefault();cancel();}}><h3 id="cf-confirm-title">{__('Confirm moderation decision')}</h3><p>{actionLabels()[request.action as keyof ReturnType<typeof actionLabels>]} · {request.items.length} {__('selected cases')}</p><p>{__('Approval publishes a checked derivative. Rejection or quarantine withdraws supported local copies. Deletion removes the retained private original. Cached copies require separate handling.')}</p><div className="cf-toolbar"><button autoFocus className="button" onClick={cancel}>{__('Cancel')}</button><button className="button button-primary" onClick={complete}>{__('Confirm decision')}</button></div></dialog>;
}
export function QueuePanel({notice}: {notice(s:string):void}) {
  const [rows,setRows]=useState<Scan[]>([]),[state,setState]=useState(''),[owner,setOwner]=useState(-1),[team,setTeam]=useState(''),[overdue,setOverdue]=useState(false),[after,setAfter]=useState(0);
  const [selected,setSelected]=useState<Set<string>>(new Set()),[detail,setDetail]=useState<Detail>(),[preview,setPreview]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
  const [reviewers,setReviewers]=useState<Reviewer[]>([]),[views,setViews]=useState<View[]>([]),[viewName,setViewName]=useState(''),[confirmation,setConfirmation]=useState<Confirmation>();
  const [caseOwner,setCaseOwner]=useState(0),[assignment,setAssignment]=useState<Assignment>({team:'',priority:0,sla_at:null});
  const requestId=useRef(0),detailRequest=useRef(0),revealRef=useRef<HTMLButtonElement>(null),detailHeading=useRef<HTMLHeadingElement>(null),queueHeading=useRef<HTMLHeadingElement>(null),opener=useRef<HTMLElement>(),caseOpener=useRef<HTMLElement>(),restoreAfterAction=useRef(false);
  useEffect(()=>{if(!confirmation)opener.current?.focus();},[confirmation]);
  useEffect(()=>{if(!busy&&restoreAfterAction.current){restoreAfterAction.current=false;const target=detail?opener.current:caseOpener.current;if(target?.isConnected&&!target.hasAttribute('disabled'))target.focus();else queueHeading.current?.focus();}},[busy,detail,rows]);
  const load=async()=>{const token=++requestId.current;setBusy(true);const query=new URLSearchParams({after:String(after),state,overdue:String(overdue)});if(owner>=0)query.set('owner',String(owner));if(team)query.set('team',team);try{const data=await api<Scan[]>('/scans?'+query);if(token===requestId.current){setRows(data);setSelected(new Set());}}catch(error){if(token===requestId.current)notice((error as Error).message);}finally{if(token===requestId.current)setBusy(false);}};
  useEffect(()=>{setRows([]);setSelected(new Set());setDetail(undefined);setPreview('');detailRequest.current++;void load();return()=>{requestId.current++;detailRequest.current++;};},[state,owner,team,overdue,after]);
  useEffect(()=>{let active=true;api<Reviewer[]>('/reviewers').then(v=>{if(active)setReviewers(v);}).catch(e=>notice(e.message));api<View[]>('/queue-views').then(v=>{if(active)setViews(v);}).catch(e=>notice(e.message));return()=>{active=false;};},[]);
  useEffect(()=>{if(detail){setCaseOwner(Number(detail.case?.owner_id??0));setAssignment({team:detail.case?.team??'',priority:Number(detail.case?.priority??0),sla_at:detail.case?.sla_at??null});detailHeading.current?.focus();}},[detail]);
  const perform=async(action:string,items:Scan[],extra:Extra={})=>{setConfirmation(undefined);restoreAfterAction.current=true;setBusy(true);try{const results=await api<BulkResult[]>('/bulk',{items:items.map(r=>({id:Number(r.id),revision:Number(r.revision)})),action,reason,...extra});const failures=bulkFailures(results);notice(failures.length?__('Some actions failed: ')+failures.join(' · '):__('Moderation action recorded.'));setDetail(undefined);setPreview('');detailRequest.current++;setSelected(new Set());await load();}catch(error){notice((error as Error).message);}finally{setBusy(false);opener.current?.focus();}};
  const act=(action:string,items:Scan[],extra:Extra={})=>{if(!items.length||busy)return;if(reason.trim().length<3){notice(__('Enter a reason of at least three characters.'));return;}opener.current=document.activeElement as HTMLElement;if(['approve','reject','quarantine','delete'].includes(action))setConfirmation({action,items,extra:{...extra,confirm:true}});else void perform(action,items,extra);};
  const open=async(row:Scan,button:HTMLElement)=>{opener.current=button;caseOpener.current=button;const token=++detailRequest.current;setPreview('');setReason('');setDetail(undefined);try{const value=await api<Detail>('/scans/'+row.id);if(token===detailRequest.current)setDetail(value);}catch(error){if(token===detailRequest.current)notice((error as Error).message);}};
  return <section><h2 ref={queueHeading} tabIndex={-1}>{__('Moderation queue')}</h2><p>{__('Uploads held here remain private. Approval publishes a security-checked derivative. Sensitive previews require an explicit reveal.')}</p>
    <div className="cf-toolbar"><label>{__('View')}<select aria-label={__('View')} disabled={busy} value={state} onChange={e=>{setState(e.target.value);setAfter(0);}}><option value="">{__('All records')}</option>{['PENDING_PROVIDER','REVIEW_REQUIRED','QUARANTINED','ALLOWED','BLOCKED','APPEALED','FAILED'].map(s=><option key={s}>{s}</option>)}</select></label><label>{__('Assigned reviewer')}<select disabled={busy} value={owner} onChange={e=>{setOwner(Number(e.target.value));setAfter(0);}}><option value={-1}>{__('Any reviewer')}</option><option value={0}>{__('Unassigned')}</option>{reviewers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>{__('Team filter')}<input disabled={busy} value={team} maxLength={64} onChange={e=>{setTeam(e.target.value);setAfter(0);}}/></label><label><input type="checkbox" disabled={busy} checked={overdue} onChange={e=>{setOverdue(e.target.checked);setAfter(0);}}/>{__('Past review deadline')}</label><button className="button" disabled={busy} onClick={load}>{__('Refresh')}</button></div>
    <div className="cf-toolbar"><label>{__('Saved queue view')}<select value="" disabled={busy} onChange={e=>{const v=views.find(v=>v.id===e.target.value);if(v){setState(v.state);setOwner(v.owner);setTeam(v.team);setOverdue(v.overdue);setAfter(0);}}}><option value="">{__('Choose saved view')}</option>{views.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>{__('View name')}<input value={viewName} maxLength={80} onChange={e=>setViewName(e.target.value)}/></label><button className="button" disabled={busy||!viewName.trim()||views.length>=10} onClick={async()=>{try{setViews(await api<View[]>('/queue-views/save',{views:[...views,{id:'view-'+crypto.randomUUID().slice(0,8),name:viewName.trim(),state,owner,team,overdue}]}));setViewName('');notice(__('Queue view saved.'));}catch(error){notice((error as Error).message);}}}>{__('Save queue view')}</button>{views.length>0&&<button className="button" disabled={busy} onClick={async()=>{try{setViews(await api<View[]>('/queue-views/save',{views:[]}));notice(__('Saved views cleared.'));}catch(error){notice((error as Error).message);}}}>{__('Clear saved views')}</button>}</div>
    {busy&&<wp.components.Spinner/>}<table className="widefat striped"><caption className="screen-reader-text">{__('Private moderation cases')}</caption><thead><tr><th>{__('Select')}</th><th>{__('File / case')}</th><th>{__('State')}</th><th>{__('Risk signal')}</th><th>{__('Assignment / deadline')}</th><th>{__('Created')}</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><input type="checkbox" aria-label={__('Select case')+' '+row.id} checked={selected.has(row.id)} onChange={e=>{const next=new Set(selected);e.target.checked?next.add(row.id):next.delete(row.id);setSelected(next);}}/></td><td><button className="button-link" disabled={busy} onClick={e=>void open(row,e.currentTarget)}>{row.file_name}</button> <small>#{row.id}</small></td><td><span className="cf-state">{row.state}</span></td><td>{Number(row.risk).toLocaleString(intlLocale(CFConfig.locale),{style:'percent'})}</td><td>{reviewers.find(r=>String(r.id)===row.owner_id)?.name??__('Unassigned')}{row.team&&' · '+row.team}{row.sla_at&&<div>{date(row.sla_at)}</div>}</td><td>{date(row.created_at)}</td></tr>)}</tbody></table>{!rows.length&&!busy&&<p className="cf-empty">{__('No cases match this view.')}</p>}
    <div className="cf-toolbar"><button className="button" disabled={!after||busy} onClick={()=>setAfter(0)}>{__('First page')}</button><button className="button" disabled={rows.length<30||busy} onClick={()=>setAfter(Number(rows[rows.length-1].id))}>{__('Next page')}</button></div>
    <label className="cf-reason">{__('Required moderation reason')}<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000}/></label><div className="cf-toolbar"><button className="button button-primary" disabled={!selected.size||busy} onClick={()=>act('approve',rows.filter(r=>selected.has(r.id)))}>{__('Approve selected')}</button><button className="button" disabled={!selected.size||busy} onClick={()=>act('reject',rows.filter(r=>selected.has(r.id)))}>{__('Reject selected')}</button></div>
    {detail&&<div className="cf-card"><h3 ref={detailHeading} tabIndex={-1}>{detail.file_name} · #{detail.id}</h3><p><strong>{detail.decision.action}</strong> · {(detail.decision.reasons??[]).join(', ')} · {(detail.decision.rules??[]).join(', ')}</p><p className="cf-warning">{__('Content warning: this preview may contain sensitive or disturbing material.')}</p>{preview?<><img className="cf-preview" src={preview} alt={__('Revealed moderation preview')}/><button className="button" onClick={()=>{setPreview('');revealRef.current?.focus();}}>{__('Hide preview')}</button></>:<button ref={revealRef} className="button" disabled={busy||!CFConfig.caps.reveal_sensitive_content} onClick={async()=>{try{const token=detailRequest.current;const result=await api<{mime:string;content:string}>('/scans/'+detail.id+'/preview');if(!['image/jpeg','image/png','image/gif','image/webp','image/avif'].includes(result.mime))throw new Error(__('Unsupported preview.'));if(token===detailRequest.current)setPreview('data:'+result.mime+';base64,'+result.content);}catch(error){notice((error as Error).message);}}}>{__('Reveal sensitive preview')}</button>}
      <Credentials detail={detail}/><fieldset className="cf-card"><legend>{__('Case assignment')}</legend><div className="cf-toolbar"><label>{__('Case reviewer')}<select value={caseOwner} onChange={e=>setCaseOwner(Number(e.target.value))}><option value={0}>{__('Unassigned')}</option>{reviewers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>{__('Case team')}<input maxLength={64} value={assignment.team} onChange={e=>setAssignment({...assignment,team:e.target.value})}/></label><label>{__('Case priority')}<input type="number" min={0} max={1000} value={assignment.priority} onChange={e=>setAssignment({...assignment,priority:Number(e.target.value)})}/></label><label>{__('Review deadline (UTC)')}<input type="datetime-local" value={assignment.sla_at?.replace(' ','T').slice(0,16)??''} onChange={e=>setAssignment({...assignment,sla_at:e.target.value?e.target.value.replace('T',' ')+':00':null})}/></label><button className="button" disabled={busy} onClick={()=>act('assign',[detail],{owner_id:caseOwner,assignment})}>{__('Save assignment')}</button></div></fieldset>
      {(detail.appeals??[]).length>0&&<details open><summary>{__('Uploader review requests')}</summary>{detail.appeals?.map((a,i)=><p key={i}>{date(a.created_at)} · {a.status} · {a.reason}{a.resolution&&' · '+a.resolution}</p>)}</details>}
      <details><summary>{__('Moderator notes and rationale')}</summary>{(detail.notes??[]).map((n,i)=><p key={i}><strong>{n.action}</strong> · {date(n.created_at)} · {n.reason}</p>)}</details><table className="widefat"><caption>{__('Normalized evidence')}</caption><thead><tr><th>{__('Category')}</th><th>{__('Score and scale')}</th><th>{__('Provider / model')}</th></tr></thead><tbody>{detail.findings.map((f,i)=><tr key={i}><td>{f.category}</td><td>{f.confidence.toFixed(3)} ({f.scale})</td><td>{f.provider} / {f.model}</td></tr>)}</tbody></table><div className="cf-toolbar">{Object.entries(actionLabels()).map(([action,label])=><button key={action} className="button" disabled={busy} onClick={()=>act(action,[detail])}>{label}</button>)}<button className="button" onClick={()=>{setDetail(undefined);setPreview('');detailRequest.current++;if(caseOpener.current?.isConnected)caseOpener.current.focus();else queueHeading.current?.focus();}}>{__('Close case')}</button></div></div>}
    {confirmation&&<Confirm request={confirmation} cancel={()=>{setConfirmation(undefined);opener.current?.focus();}} complete={()=>void perform(confirmation.action,confirmation.items,confirmation.extra)}/>}
  </section>;
}
