import type * as React from 'react';
import {api,__} from './transport';
import type {Finding,Policy} from './model';
declare const wp:{element:typeof React};
const {createElement:h,useState,useRef,useEffect}=wp.element;
type Report={published:false;decision:{shadow:boolean;risk:number;action:string;reasons:string[];rules:string[];policy_id:string;policy_version:number};findings:Finding[];duration_ms:number;estimated_cost:number;providers:{provider:string;model:string;error:string|null;duration_ms:number;estimated_cost:number;language:string}[]};
export function FileSimulation({policy,notice}:{policy:Policy;notice(s:string):void}) {
  const [file,setFile]=useState<File>(),[busy,setBusy]=useState(false),[result,setResult]=useState<Report>();const active=useRef(true);
  useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
  return <form className="cf-card" onSubmit={async e=>{e.preventDefault();if(!file||busy)return;setBusy(true);setResult(undefined);const body=new FormData();body.append('file',file);body.append('policy',JSON.stringify(policy));try{const value=await api<Report>('/simulation/file',body);if(active.current)setResult(value);}catch(error){if(active.current)notice((error as Error).message);}finally{if(active.current)setBusy(false);}}}>
    <h3>{__('Simulate a sample file')}</h3><p>{__('The sample is analyzed privately and never published. Configured providers may process reduced media and consume your request budget. Raw sample files and extracted words are discarded after this test. Use lawful samples only.')}</p><label>{__('Policy sample file')}<input type="file" required disabled={busy} onChange={e=>{setFile(e.target.files?.[0]);setResult(undefined);}}/></label><button className="button" disabled={busy||!file}>{busy?__('Analyzing sample…'):__('Analyze without publishing')}</button>
    {result&&<div role="status"><p><strong>{result.decision.action}</strong> · {result.decision.policy_id} / {result.decision.policy_version} · {result.decision.rules.join(', ')||__('Default or confidence band')}</p>{result.decision.shadow&&<p>{__('Monitor decision: security-approved media would be allowed by enforcement.')}</p>}<p>{result.decision.reasons.join(', ')}</p><p>{__('Risk signal')}: {result.decision.risk.toFixed(3)}</p><p>{__('Analysis time (ms)')}: {Math.round(result.duration_ms)} · {__('Estimated provider cost')}: {result.estimated_cost}</p><p>{__('Sample was not published.')}</p><table className="widefat"><caption>{__('Sample normalized findings')}</caption><thead><tr><th>{__('Category')}</th><th>{__('Score and scale')}</th><th>{__('Provider / model')}</th></tr></thead><tbody>{result.findings.map((f,i)=><tr key={i}><td>{f.category}</td><td>{f.confidence.toFixed(3)} ({f.scale})</td><td>{f.provider} / {f.model}</td></tr>)}</tbody></table><ul>{result.providers.map((p,i)=><li key={i}>{p.provider} / {p.model} · {p.error??__('Measured')} · {Math.round(p.duration_ms)} ms · {p.estimated_cost}{p.language&&' · '+p.language}</li>)}</ul></div>}
  </form>;
}
