import type * as React from 'react';
import {api, __} from './transport';
import type {Policy} from './model';
declare const wp: {element: typeof React; components: {Spinner: React.ComponentType}};
const {createElement:h, Fragment, useState, useEffect, useRef} = wp.element;
export type PluginSettings = {require_malware:boolean; publication_gate:boolean; privacy_retain_audit:boolean; onboarding_complete:boolean; delete_on_uninstall:boolean; enable_documents:boolean;enable_temporal:boolean;enable_provenance:boolean;max_bytes:number; max_pixels:number; monthly_cap:number; upload_per_hour:number; sla_hours:number; allowed_extensions?:string[]; retention:Record<string,number>;processing:{max_duration:number;max_frames:number;max_pages:number;sampling:string}};
const settingLabels = () => ({require_malware:__('Require malware scanner'),publication_gate:__('Require approved media before publishing'),privacy_retain_audit:__('Retain audit records during personal-data erasure'),delete_on_uninstall:__('Delete plugin data on uninstall'),max_bytes:__('Maximum upload bytes'),max_pixels:__('Maximum image pixels'),monthly_cap:__('Monthly provider request limit'),upload_per_hour:__('Uploads per user per hour'),sla_hours:__('Review deadline in hours')});
const retentionLabels = () => ({private_files_days:__('Private originals (days)'),safe_metadata_days:__('Accepted scan metadata (days)'),blocked_metadata_days:__('Held or rejected scan metadata (days)'),audit_days:__('Audit events (days)'),analytics_days:__('Analytics and feedback (days)'),job_days:__('Completed or failed jobs (days)')});
const nativeLabels = () => ({enable_documents:__('Enable PDF reconstruction and page inspection'),enable_temporal:__('Enable video and audio processing'),enable_provenance:__('Enable offline Content Credentials verification')});
const processingLabels = () => ({max_duration:__('Maximum media duration (seconds)'),max_frames:__('Maximum sampled video frames'),max_pages:__('Maximum PDF pages')});
const extensions=['jpg','jpeg','png','webp','gif','avif','svg','pdf','txt','zip','docx','xlsx','pptx','mp3','wav','ogg','m4a','mp4','webm'];
function MediaFields({value,change,files}: {value:PluginSettings;change(v:PluginSettings):void;files:boolean}) {
  return <><fieldset className="cf-card"><legend>{__('Media processing')}</legend><p>{__('Enable these options after the administrator has configured and tested the required local tools. Sampled frames do not inspect every instant. Audio requires a transcription provider. Unsupported redaction stays in review.')}</p>{Object.entries(nativeLabels()).map(([key,label])=><label className="cf-setting" key={key}>{label}<input type="checkbox" checked={value[key as keyof PluginSettings]===true} onChange={e=>change({...value,[key]:e.target.checked})}/></label>)}{Object.entries(processingLabels()).map(([key,label])=><label className="cf-setting" key={key}>{label}<input type="number" min={1} max={key==='max_duration'?600:key==='max_frames'?32:100} required value={Number(value.processing[key as keyof PluginSettings['processing']])} onChange={e=>change({...value,processing:{...value.processing,[key]:Number(e.target.value)}})}/></label>)}<label className="cf-setting">{__('Video sampling')}<select value={value.processing.sampling} onChange={e=>change({...value,processing:{...value.processing,sampling:e.target.value}})}><option value="uniform">{__('Uniform')}</option><option value="scene">{__('Scene changes')}</option><option value="adaptive">{__('Interval and scene changes')}</option></select></label></fieldset>
    {files&&<fieldset className="cf-card"><legend>{__('Permitted file extensions')}</legend><p>{__('WordPress must also permit the file type. Office documents and archives remain held without a supported reconstruction path.')}</p>{extensions.map(extension=><label className="cf-setting" key={extension}>{extension}<input type="checkbox" checked={(value.allowed_extensions??['jpg','jpeg','png','webp','gif','avif','pdf','txt']).includes(extension)} onChange={e=>{const selected=value.allowed_extensions??['jpg','jpeg','png','webp','gif','avif','pdf','txt'];change({...value,allowed_extensions:e.target.checked?[...selected,extension]:selected.filter(v=>v!==extension)});}}/></label>)}</fieldset>}</>;
}
function Fields({value,change,includeDelete=true}: {value:PluginSettings;change(v:PluginSettings):void;includeDelete?:boolean}) {
  return <><fieldset className="cf-card"><legend>{__('Security and operating limits')}</legend>{Object.entries(settingLabels()).filter(([key])=>includeDelete||key!=='delete_on_uninstall').map(([key,label]) => {const current = value[key as keyof PluginSettings]; return <label className="cf-setting" key={key}>{label}{typeof current === 'boolean' ? <input type="checkbox" checked={current} onChange={e=>change({...value,[key]:e.target.checked})}/> : <input type="number" min={1} max={key==='sla_hours'?8760:undefined} required value={Number(current)} onChange={e=>change({...value,[key]:Number(e.target.value)})}/>}</label>;})}</fieldset><MediaFields value={value} change={change} files={includeDelete}/><fieldset className="cf-card"><legend>{__('Data retention')}</legend><p>{__('Limits are separate for each data class. Raw provider responses and OCR text are never persisted. Published WordPress files are separate from private originals.')}</p>{Object.entries(retentionLabels()).map(([key,label])=><label className="cf-setting" key={key}>{label}<input type="number" required min={1} max={3650} value={value.retention[key]} onChange={e=>change({...value,retention:{...value.retention,[key]:Number(e.target.value)}})}/></label>)}</fieldset></>;
}
export function SettingsPanel({notice}: {notice(s:string):void}) {
  const [value,setValue] = useState<PluginSettings>(); const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true; api<PluginSettings>('/settings').then(v=>{if(active)setValue(v);}).catch(e=>notice(e.message));return()=>{active=false;};},[]);
  if(!value)return <wp.components.Spinner/>;
  return <section><h2>{__('Settings')}</h2><p>{__('Configure persistent private storage and provider credentials in deployment configuration. Settings do not contain secret values.')}</p><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{setValue(await api<PluginSettings>('/settings/save',value));notice(__('Settings saved.'));}catch(error){notice((error as Error).message);}finally{setBusy(false);}}}><Fields value={value} change={setValue}/><button className="button button-primary" disabled={busy}>{__('Save settings')}</button></form></section>;
}
type Setup = {step:number;complete:boolean;policy:Policy;settings:PluginSettings;health:{persistent_private_storage:boolean;malware_configured:boolean;issues:string[];providers:{id:string}[]}};
export function OnboardingPanel({notice}: {notice(s:string):void}) {
  const [setup,setSetup]=useState<Setup>();const [presets,setPresets]=useState<Policy[]>([]);const [preset,setPreset]=useState('current');const [busy,setBusy]=useState(false);const heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{let active=true;api<Setup>('/onboarding').then(v=>{if(active)setSetup(v);}).catch(e=>notice(e.message));api<Policy[]>('/presets').then(v=>{if(active)setPresets(v);}).catch(()=>{});return()=>{active=false;};},[]);
  const save=async (value:unknown)=>{if(busy)return;setBusy(true);try{setSetup(await api<Setup>('/onboarding/save',value));notice(__('Setup progress saved.'));heading.current?.focus();}catch(error){notice((error as Error).message);}finally{setBusy(false);}};
  if(!setup)return <wp.components.Spinner/>;
  const labels=[__('Check environment'),__('Choose policy'),__('Set privacy and limits'),__('Review and finish')];
  return <section><h2 tabIndex={-1} ref={heading}>{__('Setup')}</h2><ol className="cf-steps">{labels.map((label,i)=><li key={i} aria-current={setup.step===i?'step':undefined}>{label}</li>)}</ol>{setup.complete&&<p role="status">{__('Setup is complete. You can review these settings again.')}</p>}
    {setup.step===0&&<><h3>{labels[0]}</h3><p>{__('Uploads awaiting review stay in private storage. Check your storage, scanner and worker configuration before enabling enforcement.')}</p><dl className="cf-facts"><div><dt>{__('Persistent private storage')}</dt><dd>{setup.health.persistent_private_storage?__('Configured'):__('Deployment configuration required')}</dd></div><div><dt>{__('Malware scanner')}</dt><dd>{setup.health.malware_configured?__('Configured'):__('Not configured')}</dd></div><div><dt>{__('Content providers')}</dt><dd>{setup.health.providers.map(p=>p.id).join(', ')||__('None configured')}</dd></div></dl>{setup.health.issues.length>0&&<p role="status">{setup.health.issues.join(' · ')}</p>}<button className="button button-primary" disabled={busy} onClick={()=>save({step:1})}>{__('Continue setup')}</button></>}
    {setup.step===1&&<><h3>{labels[1]}</h3><p>{__('Security Only applies local file checks. Content presets require providers capable of supplying their requested evidence. Missing evidence stays in review.')}</p><label>{__('Starting policy')}<select value={preset} onChange={e=>setPreset(e.target.value)}><option value="current">{__('Keep current policy')}</option>{presets.map(p=><option key={p.id} value={p.name}>{p.name}</option>)}</select></label><div className="cf-toolbar"><button className="button" disabled={busy} onClick={()=>save({step:0})}>{__('Back')}</button><button className="button button-primary" disabled={busy} onClick={()=>save(preset==='current'?{step:2}:{step:2,preset})}>{__('Save policy and continue')}</button></div></>}
    {setup.step===2&&<form onSubmit={e=>{e.preventDefault();const {onboarding_complete,delete_on_uninstall,allowed_extensions,...settings}=setup.settings;void save({step:3,settings});}}><h3>{labels[2]}</h3><Fields includeDelete={false} value={setup.settings} change={v=>setSetup({...setup,settings:v})}/><div className="cf-toolbar"><button type="button" className="button" disabled={busy} onClick={()=>save({step:1})}>{__('Back')}</button><button className="button button-primary" disabled={busy}>{__('Save limits and continue')}</button></div></form>}
    {setup.step===3&&<><h3>{labels[3]}</h3><p>{__('Active policy')}: {setup.policy.name} · {setup.policy.version}</p><p>{__('Run the worker every minute. Validate your provider accounts and site policy on lawful samples before automatic content enforcement.')}</p><div className="cf-toolbar"><button className="button" disabled={busy} onClick={()=>save({step:2})}>{__('Back')}</button><button className="button button-primary" disabled={busy} onClick={()=>save({step:3,complete:true})}>{__('Finish setup')}</button></div></>}
  </section>;
}
